#!/bin/bash
#$ -A <project>                       # Charge project against directive
#$ -V                                    # Inherit submission environment
#$ -cwd                                # Use current working directory
#$ -N <database>_<filter>_path                  # Job name
#$ -j y                                  # Combine STDOUT and STDERR
#$ -o $JOB_NAME.o$JOB_ID           # Name of the output file (eg. myMPI.oJobID)
#$ -pe 1way 24                     # Request 24 processors, at a rate of 24 proc/node (so 1 node)
#$ -q normal                      # Use 'normal' queue ('development' for testing, 'largemem' for lots-o-memory)
#$ -l h_rt=24:00:00                 # Run time (hh:mm:ss)
#$ -M <email>                      # Email
#$ -m baes                            # Notifications at beginning and end of job

module load pylauncher
python gene_parser_path.py <database file> <column number of gene name> '<output folder>'


# example:
# python gene_parser_path.py 2014-04-15_tcdb_1.A.1.2_blast.csv 12 './tcdb-1.A.1.2'
